# Generated by Django 5.1.3 on 2024-12-04 12:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#7BB7EC', image_field=None, max_length=25, samples=None),
        ),
    ]
